---
title: "Homework 2"
author: "Allison Randy-Cofie"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(readxl)
```
### Problem 1
```{r}
nyc = read_csv("./nyc_transit.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name,station_latitude,station_longitude, route1:route11,entry,vending,entrance_type,ada) 
```



### Problem 2

Load the datasets
```{r}
mr_df = read_excel("./Trash-Wheel-Collection-Totals-7-2020-2.xlsx","Mr. Trash Wheel","A2:N534")%>%
 janitor::clean_names() %>% 
  drop_na(year) %>% 
  mutate(sports_balls=as.integer(sports_balls)) %>% 
   mutate(trash_wheel = "mr")
```

```{r}
prof_df = read_excel("./Trash-Wheel-Collection-Totals-7-2020-2.xlsx","Professor Trash Wheel","A2:N116")%>%
 janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls=as.integer(sports_balls))%>% 
   mutate(trash_wheel = "prof")
```

Combining the data
```{r}
trash_df=bind_rows(mr_df,prof_df)
```

### Problem 3
```{r}
pols_df= read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year","month","day")) %>% 
  mutate(month = month.abb[as.numeric(month)],
  president = recode(prez_dem, `1` = "dem", `0` = "gop")) %>% 
  select(-c(prez_gop, prez_dem, day)) 
```

```{r}
snp_df = read_csv("./fivethirtyeight_datasets/snp.csv") 
dates <- snp_df$date %>% as.Date(., "%m/%d/%y")
dates <- as.Date(ifelse(dates > Sys.Date(), format(dates, "19%y-%m-%d"), format(dates)))
snp_df$date = dates

snp_df = snp_df %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year","month","day")) %>% 
  mutate(month = month.abb[as.numeric(month)]) %>% 
  arrange(year, month) %>% 
  relocate(year, month)
```

```{r}
umemp_df<- read_csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>%
   pivot_longer(
    jan:dec, 
    names_to = "month",
    values_to = "unemp_rate"
  ) %>% 
  arrange(year, month) %>% 
  relocate(year, month) %>% 
  mutate(year = as.character(year))
```


Putting them together
```{r}
final_df = 
  pols_df %>% 
  left_join(snp_df, by = c("year","month")) %>% 
  left_join(umemp_df, by = c("year", "month"))


```



